Home: Implementació de contacto flotante.
HA-Team/duit pull request #70
Opened 2020-05-19 11:52 UTC by LeviTamiozzo

2020-05-20 09:38 UTC, tomyo commented
Buenísimo!, algunas mejoras:

- [ ] Texto diálogo expandido:  Te asesoramos!
- [ ] Posibles íconos (ver cual queda mejor): 
  * https://www.vhv.rs/viewpic/mxmJhb_transparent-office-building-clipart-black-and-white-contact/
  * https://pngimage.net/wp-content/uploads/2018/05/contact-me-icon-png-4.png
- [ ] Ícono pequeño (superpuesto): dejar el de whatsapp, como en las fichas de producto.

- [ ] Cuando se expande el select de "Tipo de propiedad" del home, debería tapar el flotante.

Probablemente sea bueno: 
- [ ] Que quede arriba del footer, tipo sticky, usando la técnica del detalle de producto.

2020-05-20 13:13 UTC, tomyo requested changes
Cambios propuestos en PR

2020-05-20 15:21 UTC, LeviTamiozzo commented
> * [x]  Posibles íconos (ver cual queda mejor): **Fijate ese qué tal (a mí me gustó).**

> * [ ]  Que quede arriba del footer, tipo sticky, usando la técnica del detalle de producto. **Si´, tenía pensado esperar a que esté pusheado el nuevo footer para implementarlo así, ni bien esté ese merge lo hago sticky!**

2020-05-25 17:49 UTC, tomyo commented
![LOGOS DUIT WAPP-02](https://user-images.githubusercontent.com/708569/82834253-d30d6000-9ec0-11ea-933c-3da551e4987f.png)

2020-05-27 17:11 UTC, LeviTamiozzo commented
@tomyo Ahí le metí algunos cambios. Me falta ver cómo lo acomdo en el footer y creo que quedó, cómo lo ves?

2020-05-27 19:45 UTC, tomyo approved these changes
LGTM!

2020-06-03 09:07 UTC, merged