home contact initial implementation
HA-Team/duit pull request #72
Opened 2020-05-19 19:39 UTC by LeviTamiozzo

2020-05-20 11:11 UTC, tomyo commented
Va quedando bueno!
Algunas cositas:
- [ ] Mejorar centrado de labels dentro de inputs.
Por lo visto bootstrap le da margin-bottom a los labels, haciendo que no queden centrados dentro del input.  (Fix: averride del margin-botton para estos labels)
![image](https://user-images.githubusercontent.com/708569/82438327-26367b80-9a99-11ea-8888-854198160759.png)
- [ ] Agregar * al texto de los labels para campos obligatorios.
- [ ] Esto viendo la mala UX de la diseñadora, el título del form parece un botón, por ahora dejalo así mas simple:
![image](https://user-images.githubusercontent.com/708569/82439628-4ebf7500-9a9b-11ea-9417-3f46e4505b86.png)

Hermoso el efecto de los labels, lo resolviste de forma muy elegante. :)

2020-05-20 13:01 UTC, tomyo requested changes
Cambios especificados en el PR

2020-05-20 19:30 UTC, LeviTamiozzo commented
Fijate ahora @tomyo cómo lo ves? Es raro porque yo los veía centrado de antes a los labels, pero bueno, le saqué ese margin igual.

2020-05-25 17:31 UTC, tomyo commented
Genial, sólo el efecto del label arriba en el campo mensaje quedó sin subir suficiente.
En realidad está muy abajo en el comienzo:

![image](https://user-images.githubusercontent.com/708569/82833438-4792cf80-9ebe-11ea-8f26-c5c09fe4ad8e.png)

![image](https://user-images.githubusercontent.com/708569/82833427-3ea1fe00-9ebe-11ea-853a-cb770361b262.png)

2020-05-26 15:38 UTC, tomyo approved these changes
LGTM

2020-05-27 17:07 UTC, merged